import React from 'react'

function Returnpage() {
    return (
        <div>
            <div>
                <p>Return & Exchange Policy</p>
                <p>Refund Policy</p>
                <p>Cancellation Policy</p>
                <p>Things To Consider</p>
            </div>
            <div>
                <h3>Return & Exchange Policy</h3>
                <ul>
                    <li>The return or exchange can be done within 15 days after your order is delivered.</li>
                    <li>In case the customer receives defective/wrong product(s), the reverse pickup will be generated by us and the shipping charges will be covered by us only.</li>
                    <li><b>Note:</b> It is mandatory to capture a video/photo before shipping the package or handling it to our courier partner.</li>
                    <li>If the customer's pin code is non-serviceable by our courier partners, then the customer is liable to self-ship the product(s) and the shipping charges upto ₹100 are 100% refundable if customer receives defective/wrong product(s).</li>
                    <li>Please courier the product(s) to the following address:<br /><b>Beyoung Folks Pvt. Ltd. Eklingpura Chouraha, Ahmedabad Main Road (NH 8 - Near Mahadev Hotel) Udaipur, India 313002</b></li>
                    <li>Kindly pack the product(s) properly to prevent damage during transit. Please ensure the product(s) must be in unused condition with all tags and packaging.</li>
                    <li>Due to hygiene concerns of our customers, we do not accept return/refund or perform an exchange for the Boxer Shorts.</li>
                    <li><b>Note:</b> We suggest you to select 'Speed Post' as your courier service rather than using other courier companies. Speed Post is a government-owned entity that operates India's largest postal network and it is totally reliable
                    </li>
                </ul>
            </div>
            <div>
                <h3>Refund Policy</h3>
                <ul>
                    <li><b>Prepaid Orders:</b> The refund for the prepaid order will be processed within 7 working days after receiving your order at the warehouse and Quality Check of the product(s). The Refund Amount will be reflected in the respective payment mode.</li>
                    <p><b>Note:</b> If you've placed a prepaid order using a Refund Coupon, the Value of the Coupon Code will be refunded through a Coupon and the remaining amount will be paid through your original payment mode.</p>
                    <li><b>For COD Orders:</b> A coupon code of the ordered value will be sent to your registered email address/contact number within 48 hours after receiving your order at the warehouse and Quality Check of the product(s).
                    </li>
                </ul>
            </div>
            <div>
                <h3>Cancellation Policy</h3>
                <ul>
                    <li>The cancellation request for your order can be done within 24 hours of placing the order through the Beyoung Chatbot. Access the Chatbot from <b>My Account &gt&gt Need Help or Contact Us &gt&gt Help Centre.</b></li>
                    <li>If the order is shipped from the warehouse, it cannot be cancelled. However, if the product(s) is found to be wrong/damaged, you can raise a return request within 15 days of order delivery.</li>
                </ul>
            </div>
            <div>
                <h3>Things To Consider</h3>
                <ul>
                    <li>The customers are requested to check the size guide before placing the order.</li>
                    <li>The color of the product(s) may vary as per the customer's screen resolution.</li>
                    <li>Please provide your WhatsApp registered number for timely updates and a better shopping experience.</li>
                    <li>Due to hygiene concerns of our customers, we do not accept return/refund or perform an exchange for the Boxer Shorts.</li>
                    <li>If the customer receives a torn parcel/unrelated product(s)/empty parcel, they are requested to raise a query within 48 hours of delivery. For a safer side, we suggest our customers to create an unboxing video of the parcel too.</li>
                </ul>
            </div>
        </div>
    )
}

export default Returnpage